Repository bcgov-elmsd/workbc-ches-email-blast, pull requests merged in 2023-09, with the labels that each got.

#52 TECH-401: Update import-script to reflect the finalized .csv
  packages/cron/prisma/schema.prisma
  packages/forms-frontend/prisma/schema.prisma
  packages/import-script/.gitignore
  packages/import-script/README.md
  packages/import-script/main.py
  packages/import-script/sample.csv
Labels: enhancement

#53 TECH-397: Implement finalized Reminder email
  README.md
  packages/cron/.env.sample
  packages/cron/src/app.ts
  packages/cron/src/services/email.service.ts
  packages/cron/src/templates/previous.template.ts
  packages/cron/src/templates/reminder.template.ts
  packages/cron/src/tests/email.controller.test.ts
  packages/cron/src/tests/email.service.test.ts
  packages/cron/src/tests/templates.test.ts
  packages/forms-frontend/utils/email_templates/shortform.ts
Labels: enhancement

#58 Reminder email
  README.md
  packages/cron/src/services/email.service.ts
  packages/cron/src/templates/email1.template.ts
  packages/cron/src/templates/email2.template.ts
  packages/cron/src/templates/reminder.template.ts
  packages/cron/src/tests/templates.test.ts
Labels: enhancement

#75 fix cron job timing
  packages/cron/src/app.ts
  packages/cron/src/templates/email1.template.ts
  packages/cron/src/templates/email2.template.ts
  packages/cron/src/templates/previous.template.ts
  packages/cron/src/tests/templates.test.ts
Labels: bug

#76 Test Deployment
  packages/cron/src/app.ts
  packages/cron/src/templates/email1.template.ts
  packages/cron/src/templates/email2.template.ts
  packages/cron/src/templates/previous.template.ts
  packages/cron/src/tests/templates.test.ts
  packages/import-script/reminder.py
Labels: deployment

#77 Prod Deployment
  packages/cron/src/app.ts
  packages/cron/src/templates/email1.template.ts
  packages/cron/src/templates/email2.template.ts
  packages/cron/src/templates/previous.template.ts
  packages/cron/src/tests/templates.test.ts
  packages/import-script/reminder.py
Labels: deployment
