Repository bcgov-elmsd/workbc-ches-email-blast, pull requests merged in 2023-08, with the labels that each got.

#29 TECH-368
  packages/forms-frontend/app/api/form/route.ts
  packages/forms-frontend/app/favicon.ico
  packages/forms-frontend/app/form/page.tsx
  packages/forms-frontend/app/layout.tsx
  packages/forms-frontend/prisma/schema.prisma
Labels: enhancement

#30 TECH-363
  packages/cron/src/services/email.service.ts
  packages/cron/src/templates/email1.template.ts
  packages/cron/src/templates/email2.template.ts
Labels: enhancement

#34 Test Deployment Aug 9th
  .github/workflows/CD-dev.yml
  openshift/dc.yaml
  packages/cron/.dockerignore
  packages/cron/prisma/schema.prisma
  packages/cron/src/services/email.service.ts
  packages/forms-frontend/app/api/form/route.ts
  packages/forms-frontend/app/form/page.tsx
  packages/forms-frontend/prisma/schema.prisma
  packages/import-script/main.py
Labels: deployment

#36 TECH-384: Working group feedbacks
  package-lock.json
  packages/forms-frontend/app/form/page.tsx
Labels: bug

#37 Update test deployment
  package-lock.json
  packages/forms-frontend/app/form/page.tsx
Labels: deployment

#42 TECH-364: Implement finalized Refusal and Success page
  package-lock.json
  packages/forms-frontend/app/form/refusal/page.tsx
  packages/forms-frontend/app/form/success/page.tsx
Labels: enhancement

#39 TECH-385: Error handling on api route
  packages/forms-frontend/app/api/form/route.ts
Labels: enhancement

#40 TECH-386: update email template buttons
  packages/cron/src/templates/email1.template.ts
  packages/cron/src/templates/email2.template.ts
Labels: bug

#44 Tech-396: Fix email template inconsistencies
  packages/cron/src/templates/email1.template.ts
  packages/cron/src/templates/email2.template.ts
Labels: bug

#46 TECH-398: Added email sent time logging
  packages/cron/prisma/schema.prisma
  packages/cron/src/services/email.service.ts
  packages/cron/src/tests/email.controller.test.ts
  packages/cron/src/tests/email.service.test.ts
  packages/forms-frontend/prisma/schema.prisma
Labels: enhancement
