Repository bcgov-elmsd/workbc-ches-email-blast, pull requests merged in 2023-07, with the labels that each got.

#18 TECH-322: Python Import Script
  packages/cron/prisma/schema.prisma
  packages/cron/src/services/email.service.ts
  packages/forms-frontend/prisma/schema.prisma
  packages/import-script/.env.sample
  packages/import-script/.gitignore
  packages/import-script/README.md
  packages/import-script/main.py
  packages/import-script/requirements.txt
Labels: enhancement

#20 TECH-336: Adding placeholder text
  packages/forms-frontend/app/form/page.tsx
  packages/forms-frontend/utils/email_templates/shortform.ts
Labels: enhancement

#27 TECH-301: Front-end documentations
  package-lock.json
  packages/cron/package.json
  packages/forms-frontend/.env.sample
  packages/forms-frontend/README.md
  packages/forms-frontend/app/api/form/route.ts
  packages/forms-frontend/app/form/page.tsx
  packages/forms-frontend/app/page.tsx
  packages/forms-frontend/utils/email.ts
  packages/forms-frontend/utils/email_templates/shortform.ts
Labels: documentation

#24 Tech-350
  packages/cron/.dockerignore
  packages/cron/jest.config.js
  packages/cron/package.json
  packages/cron/src/db/singleton.ts
  packages/cron/src/tests/cron.service.test.ts
  packages/cron/src/tests/email.controller.test.ts
  packages/cron/src/tests/email.service.test.ts
  packages/cron/src/tests/templates.test.ts
Labels: test

#28 TECH-361
  packages/forms-frontend/app/form/page.tsx
Labels: bug
